### ISSUE TITLE
Esbuild like bundler

### ISSUE THREAD

**Issue by Valexr** [crewdevio/Snel#12]
What do you think about:

- [Esbuild bundler](https://github.com/evanw/esbuild/releases/tag/v0.11.11) 
- [Svelte-esbuild plugin](https://github.com/EMH333/esbuild-svelte) 
- [Esbuild-svelte starter with simple http server](https://github.com/AlexxNB/svelte-derver-starter) 
- [Esbuild-svelte starter with simple dev server](https://github.com/AlexxNB/svelte-esbuild-starter)

**Comment by buttercubz** [comment]
recently esbuild have experimental support for deno, so i think i will build a compatible plugin for that
