### ISSUE TITLE
How to add TailwindCSS?

### ISSUE THREAD

**Issue by Worthy-Programmer** [crewdevio/Snel#22]
Hey sorry very much, this is not an issue but an act of ignorance. How to add Tailwind CSS in snel?

**Comment by buttercubz** [comment]
hi, yes tailwind can be used with snel, I am currently creating an app with snel and tailwind, the only downside is that it must be used by cdn and it's a bit limited that way.

in your index.html

```html
<link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet"/>
```

**Comment by Worthy-Programmer** [comment]
Hey thank you, is there any other way? Like adding to postcss of rollup. Idk Im not well into rollup.

**Comment by buttercubz** [comment]
> Hey thank you, is there any other way? Like adding to postcss of rollup. Idk Im not well into rollup.

snel have already include postcss support

https://github.com/crewdevio/Snel/blob/1e16fff70848d910e2364bbe42d9f5f7f61465d6/compiler/build.ts#L40
