### ISSUE TITLE
Snel command don't added to Deno scripts folder

### ISSUE THREAD

**Issue by AngelNext** [crewdevio/Snel#23]
when i try to install snel with `deno run --allow-run --allow-read https://deno.land/x/snel@v0.5.3/install.ts` it gives me an error:

```js
NotFound: System cannot find specified file (os error 2)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at opRun (deno:runtime/js/40_process.js:20:17)
    at Object.run (deno:runtime/js/40_process.js:104:17)
    at install (https://deno.land/x/snel@v0.5.3/install.ts:10:24)
    at Main (https://deno.land/x/snel@v0.5.3/install.ts:24:9)
    at https://deno.land/x/snel@v0.5.3/install.ts:29:3
```

**System:** Windows 10
**Terminal:** Powershell
**Deno Version:** 1.10.3

**Comment by buttercubz** [comment]
Please update deno to lastest version

**Comment by AngelNext** [comment]
Thx doesn't give me the error now, a little question

> 
> 
> Please update deno to lastest version

Thx, it helped, a little question, is there a way to modify install location?

**Comment by AngelNext** [comment]
Ok i was wrong, the error is gone but i cannot use snel command, in fact, when i go to scripts from deno, i don't see snel

**Comment by buttercubz** [comment]
i can't reproduce on windows 10 and deno v1.11.2

**Comment by buttercubz** [comment]
try with this:

```console
deno install -A --unstable -f -r -n snel --no-check https://raw.githubusercontent.com/crewdevio/Snel/main/cli.ts
```

**Comment by AngelNext** [comment]
> 
> 
> try with this:
> 
> ```
> deno install -A --unstable -f -r -n snel --no-check https://raw.githubusercontent.com/crewdevio/Snel/main/cli.ts
> ```

Thanks you, seems to work
