### ISSUE TITLE
Dependency hell

### ISSUE THREAD

**Issue by MichailVestnik** [crewdevio/Snel#28]
Hi! 

I really like Deno for its cleanliness and simplicity. Deno is very nice to work with after the bottomless node_modules folder and endless package.json on Node.js.

But Snel has an unprecedented list of dependencies for Deno projects. 
Dependencies include large parts of the standard  library: 102, 99, 100, 66, 65, 62, 98, 97, 85 version...
Much of this duplicates itself.
A total of 25 megabytes worth of dependencies...

Are you going to fix it?

**Comment by aadamsx** [comment]
Oh geez that's not right!

**Comment by buttercubz** [comment]
hi, my apologies for the late response, i'm aware with this, i'm working to reduce the dependencies count and total size
