### ISSUE TITLE
failed to accept websocket: Error: Client 215 is not connected to { "disconnect": true }

### ISSUE THREAD

**Issue by borsemayur2** [crewdevio/Snel#30]
Getting following error after running new snel project on WSL
![image](https://user-images.githubusercontent.com/47341981/127953486-1c9853ed-9a1f-4220-98ad-8aeb1e86d682.png)

**Comment by buttercubz** [comment]
i'm aware with this, is a wocket problem i'm working to fix it

**Comment by borsemayur2** [comment]
Okay

**Comment by borsemayur2** [comment]
Thanks. None of the changes (version, wocket) are reflected in  deno repo. How to overcome that?

**Comment by buttercubz** [comment]
this problem was fixed
