### ISSUE TITLE
500 Internal Server Error caused by esm v44 after version upgrade (0.5.7)

### ISSUE THREAD

**Issue by borsemayur2** [crewdevio/Snel#31]
Import 'https://cdn.esm.sh/v44/webidl-conversions@4.0.2/deno/webidl-conversions.js' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v44/whatwg-url@7.1.0/deno/whatwg-url.js:1:0

![image](https://user-images.githubusercontent.com/47341981/128654853-f415b85f-a06b-4f6f-9dd0-79ab11d36a0d.png)

**Comment by buttercubz** [comment]
this was an error of esm.sh, it is not related to snel but it is already resolved
