### ISSUE TITLE
Uncaught SyntaxError: deno/acorn.js' does not provide an export named 'default' while installing snel

### ISSUE THREAD

**Issue by borsemayur2** [crewdevio/Snel#38]
I'm getting above error while installing snel on WSL using following command:

`deno run --allow-run --allow-read https://deno.land/x/snel/install.ts`

**Comment by buttercubz** [comment]
sorry for the late response, this is a bundler([see](https://github.com/timreichen/Bundler/issues/53)) issue and more specific an esm.sh([see](https://github.com/alephjs/esm.sh/issues)) issue

**Comment by buttercubz** [comment]
@borsemayur2  you can test from the [dev](https://github.com/crewdevio/Snel/tree/dev) branch where the problem is mitigated

**Comment by borsemayur2** [comment]
It's working. Thanks
