### ISSUE TITLE
Svelte imports resolve only works in .svelte files 

### ISSUE THREAD

**Issue by ddorstijn** [crewdevio/Snel#4]
Our application needs a store. I am used to writing this in a separate store.js file. However, the moment I tried to implement a store.js file I got the following error:  `'svelte/store' is imported by store.js, but could not be resolved – treating it as an external dependency`.

EDIT: For completion, a minimal example:

App.svelte:
``` svelte
<script>
  import { currentId } from "./store.js";
</script>

{$currentId}
```

store.js:
``` javascript
import { writable } from "svelte/store";
export const currentId = writable(0);
```

This will produce the error mentioned above.

**Comment by buttercubz** [comment]
> Our application needs a store. I am used to writing this in a separate store.js file. However, the moment I tried to implement a store.js file I got the following error: `'svelte/store' is imported by store.js, but could not be resolved – treating it as an external dependency`.

you can provide an example to try to reproduce

**Comment by buttercubz** [comment]
> store
you can try this way: 

```js
import { ... } from "https://cdn.skypack.dev/svelte/store";
```

**Comment by buttercubz** [comment]
it works importing from a url

**Comment by borsemayur2** [comment]
> 
> 
> you can try this way:
> 
> ```js
> import { ... } from "https://cdn.skypack.dev/svelte/store";
> ```

 Getting the same error for `import axiod from "https://deno.land/x/axiod.mod.ts"`

**Comment by buttercubz** [comment]
> > you can try this way:
> > ```js
> > import { ... } from "https://cdn.skypack.dev/svelte/store";
> > ```
> 
> Getting the same error for `import axiod from "https://deno.land/x/axiod.mod.ts"`

i can't reproduce it

![image](https://user-images.githubusercontent.com/47539192/113965456-64e13b80-97fb-11eb-9aca-61a2f6ac0b5c.png)

![image](https://user-images.githubusercontent.com/47539192/113965491-788ca200-97fb-11eb-9967-73a4b22c3b61.png)

please check if you using the latest version

**Comment by borsemayur2** [comment]
> 
> 
> > > > you can try this way:
> > > > ```js
> > > > import { ... } from "https://cdn.skypack.dev/svelte/store";
> > > > ```
> > > 
> > > 
> > > Getting the same error for `import axiod from "https://deno.land/x/axiod.mod.ts"`
> > 
> > 
> > i can't reproduce it
> > ![image](https://user-images.githubusercontent.com/47539192/113965456-64e13b80-97fb-11eb-9aca-61a2f6ac0b5c.png)
> > ![image](https://user-images.githubusercontent.com/47539192/113965491-788ca200-97fb-11eb-9967-73a4b22c3b61.png)
> > please check if you using the latest version
> 
> Working. There was a typo `axiod.mod.ts` instead of `axiod/mod.ts`

But i'm not able to upgrade to v0.4.0.  Trying to figure out why.
