### ISSUE TITLE
Strange error when importing https://deno.land/x/web3....

### ISSUE THREAD

**Issue by michael-spengler** [crewdevio/Snel#43]
import see highlighted code: 

<img width="1166" alt="Screenshot 2022-01-13 at 19 46 27" src="https://user-images.githubusercontent.com/43786652/149390780-d67bfc4d-cf2b-4c24-9be0-7d2c39881fdd.png">

P.S. We love what you guys are doing for svelte and deno :)

**Comment by buttercubz** [comment]
@michael-spengler looks like a rollup error, let me checkout it

**Comment by michael-spengler** [comment]
@buttercubz: 
I just came across this issue again. I could imagine that the --compat mode could be helpful in this context: 
https://deno.land/manual@v1.16.3/npm_nodejs/compatibility_mode

I'm not yet familiar enough with details of snel to know where this could be brought into action in a helpful way.

**Comment by michael-spengler** [comment]
potentially also helpful in this context: https://tyhopp.com/notes/deno-import-maps-node-compat

**Comment by buttercubz** [comment]
#61
