### ISSUE TITLE
Installation error on M1 Macbook

### ISSUE THREAD

**Issue by mihirkumar** [crewdevio/Snel#44]
Problem: I ran the installation command on my M1 Macbook Air:
`deno run --allow-run --allow-read https://deno.land/x/snel/install.ts`

and got the following error message:
```
error: Import 'https://denopkg.com/crewdevio/tools@main/tty/mod.ts' failed: 504 Gateway Timeout
    at https://denopkg.com/crewdevio/tools@main/wait/deps.ts:2:22
installation complete.
```

Solution: I ran this command again and it worked.

Suggestion: I understand this is a gateway timeout so you might want to add a few retries before returning an error message to the user.

**Comment by buttercubz** [comment]
can you try this `deno run --allow-run --allow-read -r https://deno.land/x/snel/install.ts`

**Comment by mihirkumar** [comment]
That command words just fine. Does the `-r` add a recursive loop to it? If so, that might be there more ideal way to handle the default installation command.

**Comment by buttercubz** [comment]
`-r` or `--reload` re fetch all dependencies
