### ISSUE TITLE
Strange error while just using snel.

### ISSUE THREAD

**Issue by c4p-n1ck** [crewdevio/Snel#45]
I just keep on getting this strange error message time and again while running via `trex run start` The server and the page can be reloaded and it'll be working fine for some moments while it stops to work after sometime.

```

  Compiled successfully!

  You can now view vui in the browser.

      Local:            http://localhost:2324
      

  Note that the development build is not optimized.
  To create a production build, use trex run build.
  
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
          numBytesWritten = await this.#writer.write(data);
                            ^
    at async write (deno:ext/net/01_net.js:26:12)
    at async BufWriter.write (https://deno.land/std@0.117.0/io/buffer.ts:783:29)
    at async writeResponse (https://deno.land/std@0.117.0/http/_io.ts:281:15)
    at async ServerRequest.respond (https://deno.land/std@0.117.0/http/server_legacy.ts:98:7)

```

**Comment by buttercubz** [comment]
can you provide me deno's version are u using

**Comment by c4p-n1ck** [comment]
Sure!
```
 deno --version
deno 1.18.0 (release, x86_64-unknown-linux-gnu)
v8 9.8.177.6
typescript 4.5.2


 uname -a
Linux manjaro-gnome 5.15.12-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021 x86_64 GNU/Linux
```

**Comment by c4p-n1ck** [comment]
Just wanted to update that the issues still exists, and is very mysterious, I'm currently using this stupid solution right now.
```sh
while :; do
    printf "\n[!] Starting up the  UI <dev>\n"
    trex run start
done
```

**Comment by michael-spengler** [comment]
@c4p-n1ck: 
I use snel with many of my students. None of them seemed to have the same issue so far --> it seems to be a pretty OS- / version specific thing. Could you trigger a deno upgrade before we take a detailed look into this so that we know whether the issue still exists with later versions?

**Comment by c4p-n1ck** [comment]
I confirm that the following weird issue isn't there anymore after I've changed my OS.
