### ISSUE TITLE
Docs: Using third-party components?

### ISSUE THREAD

**Issue by NfNitLoop** [crewdevio/Snel#47]
How do I use third-party Svelte components with Snel?

For example, I'd love to use https://www.npmjs.com/package/svelte-spa-router/

In npm-based Svelte, I'd just `npm install --save` that dependency, and then I could import it by name.  I tried importing it via esm.sh and others but they don't seem to be able to make a module out of its `Router.svelte` file.

**Comment by buttercubz** [comment]
see https://github.com/crewdevio/Snel/discussions/25
