### ISSUE TITLE
hostname: invalid option -- 'I'

### ISSUE THREAD

**Issue by sigmaSd** [crewdevio/Snel#48]
Looks like hostname is not the same everywhere, the one installed with archlinux doesn't have `-I` it has `-i` instead to show local ip

`hostname --version`
```
hostname (GNU inetutils) 2.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Debarshi Ray.
```

**Comment by c4p-n1ck** [comment]
It looks like that `hostname -i` always tend to return `127.0.0.1` while `hostname -I` not being available on all machine.
![image](https://user-images.githubusercontent.com/86857450/152072303-2b2a0d46-32c3-4fd1-9ec2-854c0c40007b.png)

**Comment by michael-spengler** [comment]
https://github.com/crewdevio/Snel/pull/55

**Comment by michael-spengler** [comment]
@sigmaSd & @c4p-n1ck: Thank you for pointing this out --> should be fixed via pr 55
