### ISSUE TITLE
failed to execute snel create [projectname] - error: Uncaught TypeError: Yl.plugin is not a function

### ISSUE THREAD

**Issue by jeanz6** [crewdevio/Snel#49]
If I run:
``` 
snel create myproject
```
snel fails to create a project with this error message:
```
error: Uncaught TypeError: Yl.plugin is not a function
    at https://cdn.esm.sh/v65/autoprefixer@9.8.8/deno/autoprefixer.js:57:351
    at https://cdn.esm.sh/v65/autoprefixer@9.8.8/deno/autoprefixer.js:2:9145
    at https://cdn.esm.sh/v65/autoprefixer@9.8.8/deno/autoprefixer.js:57:1697

```
OS: Arch Linux x86_64 
Kernel: 5.14.10
deno version: deno 1.17.1 (release, x86_64-unknown-linux-gnu),
v8 9.7.106.15
typescript 4.5.2

**Comment by michael-spengler** [comment]
could you try: 

```sh
trex exec snel create [project name]
```

as described here: 
https://github.com/crewdevio/Snel/blob/main/README.md

**Comment by Qusay99** [comment]
I also get the same error on Windows 10 when I try to create a new snel project using `snel create [project name]`
or even when I try to run an old one with `trex run start` within the project folder.

**Comment by ntrotner** [comment]
The `imports/bundler.ts` imports a library that hasn't been updated for months, which in turn imports `postcss` that depends on an outdated `autoprefixer`. Solution would be to update the Bundler. Obviously it would need to be checked if the newer versions are compatible, but by these two fixes I was able to install and use Snel:

[Bundler Fix](https://github.com/ntrotner/Bundler/commit/ad5ed4be4fb23c047a9eb7f69c3736198313c7be)
[Snel Fix](https://github.com/ntrotner/Snel/commit/3993324974d1ba9df40a60eaaa7e5c16e0d7c81b)
`deno run --allow-run --allow-read https://raw.githubusercontent.com/ntrotner/Snel/main/install.ts`

**Comment by jeanz6** [comment]
thanks @ntrotner  it works!!

**Comment by buttercubz** [comment]
this bug was fixed in the latest version
