### ISSUE TITLE
SvelteNext adapter?

### ISSUE THREAD

**Issue by mvolkmann** [crewdevio/Snel#5]
How does this differ from what we would have if there was a Deno adapter for SvelteNext similar to the existing Node adapter?

**Comment by RivierGrullon** [comment]
Yes, it would be basically the same but without being an adaptation of `sveltenext`

**Comment by mvolkmann** [comment]
Do you think you might create a Deno adapter for SvelteKit at some point? I haven't looked into what is required to implement a new adapter. Not sure how difficult it is.

**Comment by buttercubz** [comment]
> Do you think you might create a Deno adapter for SvelteKit at some point? I haven't looked into what is required to implement a new adapter. Not sure how difficult it is.

Hi, I've been looking at the `SvelteKit` repository a bit and I think a Deno adapter could be made although I think the most difficult part will be `vite` that depends on `esbuild`, although any idea or help will be very grateful
