### ISSUE TITLE
trex run build generates incomplete href attribute(s)

### ISSUE THREAD

**Issue by michael-spengler** [crewdevio/Snel#52]
... e.g. 
link rel="stylesheet" href="/... instead of  
link rel="stylesheet" href="./...  

this is not a problem if we serve the page e.g. via https://deno.land/x/opine --> it is however a problem if we serve the page via github pages or via visual studio code live server, ...?

**Comment by michael-spengler** [comment]
we used the following potentially relevant version:  
deno 1.17.3 (release, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2

**Comment by michael-spengler** [comment]
this could be fixed by updating https://github.com/crewdevio/Snel/blob/3df2452c0340f9c442283ad3b66cbf5b334c898d/src/cli/prepare.ts#L70

**Comment by silas-pohl** [comment]
+1
