### ISSUE TITLE
Running the install commands hangs

### ISSUE THREAD

**Issue by omar2205** [crewdevio/Snel#53]
running `deno run --allow-run --allow-read -r https://deno.land/x/snel/install.ts` hangs

`Warning Implicitly using latest version (v0.7.1) for https://deno.land/x/snel/cli.ts`

**Comment by omar2205** [comment]
even running `trex exec snel create new_proj` hangs and does nothing

**Comment by michael-spengler** [comment]
Hi @omar2205. Proposal to narrow down the issue:
Could you execute the following sequence: 
```sh
deno run --allow-run --allow-read https://deno.land/x/snel/install.ts  
snel create new_proj
```
and let us know if this hangs also. If yes, could you share your operating system + deno --version ?

**Comment by omar2205** [comment]
Thanks for your reply,

I kinda figured out the problem. It was RAM, I had 1Gb.
