### ISSUE TITLE
Issue installing Snel  ......  missing or deprecated "postcss-nesting@7.0.1" and  "postcss-preset-env@6.7.0"

### ISSUE THREAD

**Issue by Peyman-Borhani** [crewdevio/Snel#58]
Hi, 
using latest version deno, chrome, windows10,...
There is an issue with installing ...snel/install.ts
It seems that 2 files are deprecated, missing, etc...

error: Import 'https://esm.sh/v86/postcss-nesting@7.0.1/deno/postcss-nesting.js' 
failed: 500 Internal Server Error at https://esm.sh/v86/postcss-preset-env@6.7.0/deno/postcss-preset-env.js:2:2086

For example removing '@7.0.1' from the link will make this version available  'postcss-nesting@10.1.9 '

Setup: 
latest versions of  windows10 x64, bash mingw64...
deno 1.23.1 (release, x86_64-pc-windows-msvc)
v8 10.4.132.8
typescript 4.7.2

**Comment by buttercubz** [comment]
#61
