### ISSUE TITLE
Failed to install snel

### ISSUE THREAD

**Issue by jwaguirr** [crewdevio/Snel#59]
I cannot install snel with install.ts. I get an error `error: Module not found "https://denopkg.com/buttercubz/deno-rollup@next/plugins/terser/mod.ts".
    at https://deno.land/x/snel@v0.7.1/src/shared/internal_plugins.ts:13:24
error: Uncaught (in promise) "\x1b[31msomething went wrong while running \x1b[33msnel\x1b[31m\x1b[39m`

**Comment by Hexagon** [comment]
I'm having dependency issues too, cannot even get started. There seem to be various issues with dependencies. 

```
error: Module not found "https://denopkg.com/buttercubz/deno-rollup@next/plugins/terser/mod.ts".
    at https://deno.land/x/snel@v0.7.1/src/shared/internal_plugins.ts:13:24
```

I would suggest gathering each and every remote dependency in one file (import_map.json, mod.ts?), so it is easy to overview. Then only use deno.land/x with every dependency locked at a specific version. This would enhance stability significantly.

**Comment by buttercubz** [comment]
#61
