### ISSUE TITLE
snel command not found after running install.ts script

### ISSUE THREAD

**Issue by borsemayur2** [crewdevio/Snel#6]
terminal tab gets reset without any output after running the script

**Comment by borsemayur2** [comment]
this seems error while installing snel manually:
```
error: Uncaught SyntaxError: The requested module 'https://esm.sh/css-tree@1.0.0-alpha22' does not provide an export named 'parse'
import { parse as parse$3$1 } from "https://esm.sh/css-tree@1.0.0-alpha22";
         ~~~~~
    at <anonymous> (https://deno.land/x/snel@v0.2.0/compiler/core.js:7:10)
```

**Comment by buttercubz** [comment]
@borsemayur2 thanks for you report, i will fix asap this is a esm.sh issue

**Comment by buttercubz** [comment]
@borsemayur2 please try again with this `deno run --allow-run --allow-read -r https://deno.land/x/snel/install.ts`

**Comment by borsemayur2** [comment]
@buttercubz Working. Thanks for the blazing fast response (just like svelte).

**Comment by borsemayur2** [comment]
> 
> 
> @borsemayur2 please try again with this `deno run --allow-run --allow-read -r https://deno.land/x/snel/install.ts`

I'm getting `installation completed` message with this command but the version remains `v0.3.0` instead of latest `v0.4.0`. Same for manual installation with `deno install -A -f -r --no-check --unstable -n snel https://deno.land/x/snel@v0.4.0/cli.ts`

**Comment by buttercubz** [comment]
> > @borsemayur2 please try again with this `deno run --allow-run --allow-read -r https://deno.land/x/snel/install.ts`
> 
> I'm getting `installation completed` message with this command but the version remains `v0.3.0` instead of latest `v0.4.0`. Same for manual installation with `deno install -A -f -r --no-check --unstable -n snel https://deno.land/x/snel@v0.4.0/cli.ts`

my apologies i'm forget update `version.ts` file

**Comment by borsemayur2** [comment]
`Uncaught Error: [esm.sh] bucket not found` after latest code merge.
![image](https://user-images.githubusercontent.com/47341981/114112476-15ce0000-98fa-11eb-8962-694e243f8210.png)
