### ISSUE TITLE
Cannot execute install.ts on Mac m1

### ISSUE THREAD

**Issue by Valexr** [crewdevio/Snel#8]
When run `deno run --allow-run https://deno.land/x/snel/install.ts` nothing happens 🤷🏻‍♂️

**Comment by buttercubz** [comment]
@Valexr hi can you run this instead

```console
deno run --allow-run --allow-read https://deno.land/x/snel/install.ts
```

**Comment by Valexr** [comment]
> @Valexr hi can you run this instead
> 
> ```
> deno run --allow-run --allow-read https://deno.land/x/snel/install.ts
> ```

Yep! It’s working🤓tx

**Comment by buttercubz** [comment]
i'm forget add this flag in the readme 😅
